### ISSUE TITLE
missing file in melpa recipe

### ISSUE THREAD

**Issue by xendk** [emacs-php/phpstan.el#23]
The melpa recipe (https://github.com/melpa/melpa/blob/master/recipes/phpstan) is missing the `flycheck-phpstan.el` file, which means that it isn't copied when using the [straight package manager](https://github.com/raxod502/straight.el). This mean that requiring the file causes an error.

And shouldn't the old package be deleted? (https://github.com/melpa/melpa/blob/master/recipes/flycheck-phpstan)

**Comment by zonuexe** [comment]
@xendk 
What does the old package mean? From the beginning, `phpstan` and `flycheck-phpstan` were released as separate packages from the beginning. 

I am not a straight user, but `flycheck-phpstan` depends on `flycheck` and `phpstan`, so the package manager will install them recursively.  If the dependencies are not resolved automatically, install flycheck, phpstan, flycheck-phpstan in order.

Thank you.

**Comment by xendk** [comment]
@zonuexe 
How stupid of me. For some reason I assumed that it was the phpstan package that provided flycheck-support.

Sorry for the inconvenience.
