### ISSUE TITLE
Flymake

### ISSUE THREAD

**Issue by hacktivista** [emacs-php/phpstan.el#26]
I'm creating this issue just to be notified if/when flymake support gets implemented

**Comment by zonuexe** [comment]
I submitted `flymake-phpstan` recipe to MELPA. https://github.com/melpa/melpa/pull/6803

**Comment by hacktivista** [comment]
awesome :tada:

**Comment by zonuexe** [comment]
@hacktivista I'm not a Flymake user, so if you find a bug, feel free to open an issue again.
